name = "KMeansClustering"
uuid = "670bb445-d745-4272-aa1b-6ff82f84f261"
authors = ["Mark-Andr√© Schadow <m.schadow@campus.tu-berlin.de>"]
version = "0.1.0-DEV"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
DataStructures = "0.19.3"
Random = "1.11.0"
julia = "1.11"
