name = "KMeansClustering"
uuid = "670bb445-d745-4272-aa1b-6ff82f84f261"
authors = ["Mark-Andr√© Schadow <m.schadow@campus.tu-berlin.de>"]
version = "0.1.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
LinearAlgebra = "1.11.0"
Statistics = "1.11.1"
julia = "1.11"
