name = "KMeansClustering"
uuid = "670bb445-d745-4272-aa1b-6ff82f84f261"
authors = ["Mark-Andr√© Schadow <m.schadow@campus.tu-berlin.de>"]
version = "0.1.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
LinearAlgebra = "1.11.0"
Statistics = "1.11.1"
DataStructures = "0.19.3"
Random = "1.11.0"
julia = "1.11"
